add some translated files
imas-tools/gakuen-adapted-translation-data pull request #7
Opened 2024-06-03 22:46 UTC by DreamGallery

先添加了一批整理出来的翻译
在csv文件上添加了翻译，本来打算写个脚本处理，但还是手动来了，有挺多东西要检查
另外遇到一些问题想问
1. 有一些词会有强调的上标以及注音（写作读作那种），不知道如何处理，暂且没管
2. 看到实际上csv文件中省略了有一些转场的文本（narration）
3. 有一些会出现玩家名的地方{user}，主要是老师的支援卡，统一还是制作人代替了
4. 换行符还是得更具实际翻译的情况来

2024-06-03 23:51 UTC, darwintree commented
1. 目前双语是通过复用注音语法来实现的，所以注音和强调没办法用注音的形式来实现了，目前的实现可以看到佑芽的第一话的格式不符预期（注音没有进行合适的处理）。能在其他文本里看到文本的其他语法（比如字体大小颜色），可能可以拿来实现类似效果。
2. 这个有例子吗 我看一下
3. 这个最好还是按照原文来
4. 这个没问题

2024-06-03 23:52 UTC, darwintree approved these changes

2024-06-03 23:56 UTC, darwintree requested changes
csprt-3-0007已经有其他人翻译了，如果要修改翻译要另行开一个pr，指出修改的部分。目前缺一个ci文件来检查pr提交的有效性，我之后会加上

2024-06-04 00:20 UTC, DreamGallery commented
> 1. 目前双语是通过复用注音语法来实现的，所以注音和强调没办法用注音的形式来实现了，目前的实现可以看到佑芽的第一话的格式不符预期（注音没有进行合适的处理）。能在其他文本里看到文本的其他语法（比如字体大小颜色），可能可以拿来实现类似效果。
> 2. 这个有例子吗 我看一下
> 3. 这个最好还是按照原文来
> 4. 这个没问题

2这个不知道你们是如何从adv文本文件提取文本的，除开choice，有两个种类是"message", "narration"，不过过场出现的不多，我提交的这些里面感觉看到过三四局，比如china的好感度第一话，一开始会有一个这样的过场
```
[narration text=――倉本邸。 clip=\{"_startTime":9.9333332656,"_duration":1.4400002241,"_clipIn":0.0,"_easeInDuration":0.0,"_easeOutDuration":0.0,"_blendInDuration":-1.0,"_blendOutDuration":-1.0,"_mixInEaseType":1,"_mixInCurve":\{"serializedVersion":"2","m_Curve":[],"m_PreInfinity":2,"m_PostInfinity":2,"m_RotationOrder":4\},"_mixOutEaseType":1,"_mixOutCurve":\{"serializedVersion":"2","m_Curve":[],"m_PreInfinity":2,"m_PostInfinity":2,"m_RotationOrder":4\},"_timeScale":1.0\}]
```
因为csv里面没有，我就没额外自己加。
另外还有一些类似过了一天什么的或者指出地名的过场
3的话文本里应该主要就老师称呼玩家会有，不过个人感觉{user}这边如果你们不会做什么特殊处理的话直接替换为プロデューサー会挺好。要按原文来的话可能之后需要改一下，下次我提交其他的再一起改吧

关于那个已经有人提交的翻译，还需要我进行额外操作吗

2024-06-04 00:25 UTC, DreamGallery commented
> > 1. 目前双语是通过复用注音语法来实现的，所以注音和强调没办法用注音的形式来实现了，目前的实现可以看到佑芽的第一话的格式不符预期（注音没有进行合适的处理）。能在其他文本里看到文本的其他语法（比如字体大小颜色），可能可以拿来实现类似效果。
> > 2. 这个有例子吗 我看一下
> > 3. 这个最好还是按照原文来
> > 4. 这个没问题
> 
> 2这个不知道你们是如何从adv文本文件提取文本的，除开choice，有两个种类是"message", "narration"，不过过场出现的不多，我提交的这些里面感觉看到过三四局，比如china的好感度第一话，一开始会有一个这样的过场
> 
> ```
> [narration text=――倉本邸。 clip=\{"_startTime":9.9333332656,"_duration":1.4400002241,"_clipIn":0.0,"_easeInDuration":0.0,"_easeOutDuration":0.0,"_blendInDuration":-1.0,"_blendOutDuration":-1.0,"_mixInEaseType":1,"_mixInCurve":\{"serializedVersion":"2","m_Curve":[],"m_PreInfinity":2,"m_PostInfinity":2,"m_RotationOrder":4\},"_mixOutEaseType":1,"_mixOutCurve":\{"serializedVersion":"2","m_Curve":[],"m_PreInfinity":2,"m_PostInfinity":2,"m_RotationOrder":4\},"_timeScale":1.0\}]
> ```
> 
> 因为csv里面没有，我就没额外自己加。 另外还有一些类似过了一天什么的或者指出地名的过场 3的话文本里应该主要就老师称呼玩家会有，不过个人感觉{user}这边如果你们不会做什么特殊处理的话直接替换为プロデューサー会挺好。要按原文来的话可能之后需要改一下，下次我提交其他的再一起改吧
> 
> 关于那个已经有人提交的翻译，还需要我进行额外操作吗

其实还有个title的种类，主要在组合/主线的剧情，就unit开头的那个，不过看内容可以忽略，只是第一话第二话那种

2024-06-04 00:31 UTC, DreamGallery commented
> > 1. 目前双语是通过复用注音语法来实现的，所以注音和强调没办法用注音的形式来实现了，目前的实现可以看到佑芽的第一话的格式不符预期（注音没有进行合适的处理）。能在其他文本里看到文本的其他语法（比如字体大小颜色），可能可以拿来实现类似效果。
> > 2. 这个有例子吗 我看一下
> > 3. 这个最好还是按照原文来
> > 4. 这个没问题
> 
> 2这个不知道你们是如何从adv文本文件提取文本的，除开choice，有两个种类是"message", "narration"，不过过场出现的不多，我提交的这些里面感觉看到过三四句，比如china的好感度第一话，一开始会有一个这样的过场
> 
> ```
> [narration text=――倉本邸。 clip=\{"_startTime":9.9333332656,"_duration":1.4400002241,"_clipIn":0.0,"_easeInDuration":0.0,"_easeOutDuration":0.0,"_blendInDuration":-1.0,"_blendOutDuration":-1.0,"_mixInEaseType":1,"_mixInCurve":\{"serializedVersion":"2","m_Curve":[],"m_PreInfinity":2,"m_PostInfinity":2,"m_RotationOrder":4\},"_mixOutEaseType":1,"_mixOutCurve":\{"serializedVersion":"2","m_Curve":[],"m_PreInfinity":2,"m_PostInfinity":2,"m_RotationOrder":4\},"_timeScale":1.0\}]
> ```
> 
> 因为csv里面没有，我就没额外自己加。 另外还有一些类似过了一天什么的或者指出地名的过场 3的话文本里应该主要就老师称呼玩家会有，不过个人感觉{user}这边如果你们不会做什么特殊处理的话直接替换为プロデューサー会挺好。要按原文来的话可能之后需要改一下，下次我提交其他的再一起改吧
> 
> 关于那个已经有人提交的翻译，还需要我进行额外操作吗

千奈的好感十里面也有一句
![image](https://github.com/imas-tools/gakuen-adapted-translation-data/assets/49429799/3f9ffc75-53a0-4989-af8e-09737137b61e)

2024-06-04 00:33 UTC, darwintree commented
> > 1. 目前双语是通过复用注音语法来实现的，所以注音和强调没办法用注音的形式来实现了，目前的实现可以看到佑芽的第一话的格式不符预期（注音没有进行合适的处理）。能在其他文本里看到文本的其他语法（比如字体大小颜色），可能可以拿来实现类似效果。
> > 2. 这个有例子吗 我看一下
> > 3. 这个最好还是按照原文来
> > 4. 这个没问题
> 
> 2这个不知道你们是如何从adv文本文件提取文本的，除开choice，有两个种类是"message", "narration"，不过过场出现的不多，我提交的这些里面感觉看到过三四局，比如china的好感度第一话，一开始会有一个这样的过场
> 
> ```
> [narration text=――倉本邸。 clip=\{"_startTime":9.9333332656,"_duration":1.4400002241,"_clipIn":0.0,"_easeInDuration":0.0,"_easeOutDuration":0.0,"_blendInDuration":-1.0,"_blendOutDuration":-1.0,"_mixInEaseType":1,"_mixInCurve":\{"serializedVersion":"2","m_Curve":[],"m_PreInfinity":2,"m_PostInfinity":2,"m_RotationOrder":4\},"_mixOutEaseType":1,"_mixOutCurve":\{"serializedVersion":"2","m_Curve":[],"m_PreInfinity":2,"m_PostInfinity":2,"m_RotationOrder":4\},"_timeScale":1.0\}]
> ```
> 
> 因为csv里面没有，我就没额外自己加。 另外还有一些类似过了一天什么的或者指出地名的过场 3的话文本里应该主要就老师称呼玩家会有，不过个人感觉{user}这边如果你们不会做什么特殊处理的话直接替换为プロデューサー会挺好。要按原文来的话可能之后需要改一下，下次我提交其他的再一起改吧
> 
> 关于那个已经有人提交的翻译，还需要我进行额外操作吗



> > > 1. 目前双语是通过复用注音语法来实现的，所以注音和强调没办法用注音的形式来实现了，目前的实现可以看到佑芽的第一话的格式不符预期（注音没有进行合适的处理）。能在其他文本里看到文本的其他语法（比如字体大小颜色），可能可以拿来实现类似效果。
> > > 2. 这个有例子吗 我看一下
> > > 3. 这个最好还是按照原文来
> > > 4. 这个没问题
> > 
> > 
> > 2这个不知道你们是如何从adv文本文件提取文本的，除开choice，有两个种类是"message", "narration"，不过过场出现的不多，我提交的这些里面感觉看到过三四局，比如china的好感度第一话，一开始会有一个这样的过场
> > ```
> > [narration text=――倉本邸。 clip=\{"_startTime":9.9333332656,"_duration":1.4400002241,"_clipIn":0.0,"_easeInDuration":0.0,"_easeOutDuration":0.0,"_blendInDuration":-1.0,"_blendOutDuration":-1.0,"_mixInEaseType":1,"_mixInCurve":\{"serializedVersion":"2","m_Curve":[],"m_PreInfinity":2,"m_PostInfinity":2,"m_RotationOrder":4\},"_mixOutEaseType":1,"_mixOutCurve":\{"serializedVersion":"2","m_Curve":[],"m_PreInfinity":2,"m_PostInfinity":2,"m_RotationOrder":4\},"_timeScale":1.0\}]
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 因为csv里面没有，我就没额外自己加。 另外还有一些类似过了一天什么的或者指出地名的过场 3的话文本里应该主要就老师称呼玩家会有，不过个人感觉{user}这边如果你们不会做什么特殊处理的话直接替换为プロデューサー会挺好。要按原文来的话可能之后需要改一下，下次我提交其他的再一起改吧
> > 关于那个已经有人提交的翻译，还需要我进行额外操作吗
> 
> 其实还有个title的种类，主要在组合/主线的剧情，就unit开头的那个，不过看内容可以忽略，只是第一话第二话那种

好 我回头都加上

2024-06-04 00:33 UTC, darwintree approved these changes

2024-06-04 00:33 UTC, merged